ipfs/bifrost-gateway

.github/workflows/docker-image.yml
.gitignore
Dockerfile
docker/entrypoint.sh
docker/get-docker-tags.sh
go.mod
go.sum
main.go

> This PR is based on #10
Borrows the most minimal set of conventions from Kubo and IPFS Cluster:
- every commit on main branch is can be run via own image named `main-YYYY-DD-MM-commit`
- we can also start doing releases in the future
- git tags are translated to Docker tags with the same names (`v0.0.0`)
- latest git tag is also tagged as `latest` and `release`

feat: add docker image

---

handlers.go
main.go

Just for code cleanliness and separation from the main file. I will merge it as soon as its green.

refactor: separate the handlers into their own file

---

README.md
blockstore.go
blockstore_cache.go
docs/environment-variables.md
go.mod
handlers.go
main.go
routing.go

Closes #26 (adds both logging calls and documentation for the environment variables).

feat: add info and debug logging

---

Dockerfile
blockstore.go
go.mod
go.sum

Taking https://github.com/filecoin-saturn/caboose/pull/26 for a spin, will rebase and  merge after upstream is finalized.
cc @aarshkshah1992  @hacdias (for visibility)

feat: switch to weighted caboose

---

blockstore.go
go.mod
go.sum

Closes #41
by applying fixes from https://github.com/filecoin-saturn/caboose/pull/19

fix: new caboose and timeouts

---

Dockerfile
README.md
docs/environment-variables.md
main.go

Partially addresses #43 (two first items).

feat!: use env variables for all flags but ports

---

blockstore.go
blockstore_test.go
go.mod
go.sum

This PR aims to use cooldown and seturn it in `Retry-After` header to the client.
Based on https://github.com/ipfs/go-libipfs/pull/194

feat: pass Retry-After to end user

---

lib/graph_gateway.go

This PR adds a basic metric to see where byte ranges usually start, and how big they are.
This info will be useful for Rhea/Saturn, allow us to reason around cache optimizations.
Adding in Saturn-specific code-path as we don't know if these give us correct visibility – will refine in future PR, if needed.

feat: byte range metrics

---

go.mod
go.sum

Includes:
https://github.com/filecoin-saturn/caboose/pull/84 
https://github.com/filecoin-saturn/caboose/pull/83 
https://github.com/filecoin-saturn/caboose/pull/82
Diff: https://github.com/filecoin-saturn/caboose/compare/e4b1e88476d9...34e6ab0f0e60ed6bef02b06242573aa5ab06bd37
cc @aarshkshah1992 @willscott

fix(caboose): metrics and context cancellations

---

version.json

(same as 0.0.2, testing fix for https://github.com/ipfs/bifrost-gateway/issues/84)

chore: 0.0.3

---

lib/graph_gateway.go

~40% requests to Caboose by Bifrost for CAR fetches are made with a context that is already cancelled
~22% requests fail as the context is cancelled while the Caboose CAR fetch is in progress.
https://protocollabs.grafana.net/d/6g0_YjBVk/bifrost-caboose-staging?orgId=1&from=now-1h&to=now&editPanel=35
We need to look into what's going on in Bifrost,

feat: measure context cancellation for CAR fetches

---

go.mod
go.sum

This PR includes latest commit from https://github.com/filecoin-saturn/caboose/pull/86, as requested by @aarshkshah1992 
I'll deploy it to staging shortly. Note that tomorrow is the last day before IPFS Thing travel and my availability 14-20th will be limited.

feat: experimental caboose pool management

---

README.md

strn.network has been migrated to saturn.tech

strn.network -> saturn.tech

---

.github/workflows/docker-image.yml

fix(ci): trigger docker image publish on automatic releases

---

lib/graph_gateway.go

Limits how many other exchanges / notifiers are notified.
Aims to fix https://github.com/ipfs/bifrost-gateway/issues/92

fix: break graph api notifiers across a sync map

---

go.mod
go.sum

Update Caboose deps to use https://github.com/filecoin-saturn/caboose/pull/86 now that it has landed
Let's deploy this to staging first for a sanity check.

Update Caboose to use the latest

---

go.mod
go.sum
routing.go

@lidel just removing a few lines of code.

refactor: simplify ipns validation

---

blockstore_caboose.go

Enable HTTP1

---

version.json

Update bifrost version to use HTTP1

---

lib/graph_gateway.go

Timeout reads if no new block of a car has been received in X amount of time
Closes #91

fix: timeout CAR fetch if no new block

---

version.json

For https://github.com/ipfs/bifrost-gateway/pull/121

Update to 0.0.7

---

lib/graph_gateway.go

previously, when calling `Next` on a car stream and getting an error - the `nil` block would be put on the block channel, and fail to be put into the block store by the other thread. This is now conditioned, and this error case is watched for.

better handling of partial errors

---

README.md

Some diagrams from [the talk I gave during IPFS Thing 2023](https://www.youtube.com/watch?v=xhJPz_efAQE&t=5s&pp=ygUcYmlmcm9zdC1nYXRld2F5IHNlbGYtaG9zdGluZw%3D%3D)

docs: updated design diagrams

---

go.mod
go.sum

Includes https://github.com/ipfs/boxo/pull/319
Closes #136

fix: panic in get

---

version.json

Release Bifrost 0.0.9 with the fix for closing block based subscription when no longer needed.

Release Bifrost 0.0.9

---

lib/graph_gateway.go

guarantees that read errors are checked after all blocks are processed.

pass block,err tuple through block channel instead of just block

---

.github/workflows/gateway-conformance.yml

feat: update conformance to v0.2

---

go.mod
go.sum

Caboose version to add sentinel cid requests

add sentinel cid requests to caboose

---

blockstore_caboose.go

increase compliance cid frequency in prod.

feat: increase compliance cid frequency

---

blockstore_caboose.go
go.mod
go.sum

rolling back caboose version to exclude compliance cid work.

fix: roll back caboose version

---

blockstore_caboose.go
go.mod
go.sum

Reverts ipfs/bifrost-gateway#167

Revert "fix: roll back caboose version"

---

go.mod
handlers.go
lib/blockstore_cache.go
lib/graph_gateway.go

get back to a stable 'main' branch.

Revert "Unshared blockstore"

---

go.mod
go.sum
handlers.go
main.go

Include the x-bfid header on request contexts

---

.github/workflows/gateway-conformance.yml

This PR adds tests from https://github.com/ipfs/bifrost-gateway/pull/190 on top of https://github.com/ipfs/bifrost-gateway/pull/160 to see if it passes when `GRAPH_BACKEND=true`

test: backpressure PR conformance with GRAPH_BACKEND=true

---

go.mod
go.sum

Update Caboose with a change of reverting the relative correctness policy in Caboose.

Update caboose for release

---

go.mod
go.sum

Use caboose version that forwards x-bfid header to L1s

Update caboose to v0.0.6

---

README.md
docs/environment-variables.md

Cosmetic updates of Markdown docs in the context of `IPNS_RECORD_GATEWAY_URL`

docs: cleanup outdated info
