main.go

Exposes `ipfs_http_response_size_bytes_sum` according to https://github.com/ipfs/bifrost-gateway/issues/8#issuecomment-1421974710, also caboose metrics.

feat: expose ipfs_http_response_size_bytes_sum and caboose metrics

---

main.go

Closes #13. I also implemented @aschmahmann comment regarding `dag/export`. I checked the API and there are no additional options that could lead to incompatibilities. The only option is `progress` which is useless for remote calls.

feat: smart /api/v0 handling

---

gateway.go
go.mod
routing.go

See https://github.com/ipfs/bifrost-gateway/pull/10#discussion_r1099587452.
Also fixes the `routing.GetValue` call. I confused it with the `CoreAPI.Routing().Get()` which expects the path as a string. `routing.ValueStore` expects the multihash encoded version of the path.
Also added this improvement and fix to the Gateway example: https://github.com/ipfs/go-libipfs/pull/158
Hopefully all this errors will be caught once we run this against the gateway tests.

fix(ipns): fail fast and fix rpc encoding

---

blockstore.go

Adds a timeout for fetching a block of 30s, such that we do not let users waiting indefinitely (#21). Perhaps we should tackle it and make it a different number.

feat: introduce block fetching timeout (30s)

---

routing.go

This is the same as /api/v0/routing/get atm, but has the benefit of being already exposed on *.delegate.ipfs.io
Means @gmasgras  has less work to do in https://github.com/protocol/bifrost-infra/issues/2327

fix: switch to /api/v0/dht/get

---

handler_test.go
handlers.go

This PR makes two changes:
- RPC API that redirects to Gateway uses **303 See Other**, as it [ensures](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303) the new request uses GET - and the gateway is GET only. 302 does [not ensure](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302) as it is underspecified.
- RPC API that redirects to a different Kubo node uses **307 Temporary Redirect**, to ensure the new request [preserves](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) the method and body of the original request.
Additionally, it fixes the redirects to support IPFS paths and not only CIDs, as that's how the API behaves. It also adds tests to ensure the redirects have the correct Location and status code.

fix: ensure correct Method and Location on RPC API redirect

---

blockstore.go

per-block timeout was introduced in https://github.com/ipfs/bifrost-gateway/pull/29 
we have `proxy_read_timeout 60;` on LB nodes, so the old setup on `ipfs.io` will cut-off after 60s of not receiving any new bytes from Kubo.
This PR should align  bifrost-gateway behavior closer to what the old setup did, which will help us compare latency and errors.
We most likely will adjust it in near future, but for M0.2 we want to compare apples to kinda-the-same-size-oranges.

chore: adjust GetBlockTimeout to 60s

---

Dockerfile
blockstore_caboose.go
blockstore_proxy.go
docs/environment-variables.md
handlers.go
http_client.go
http_client_test.go
main.go
routing.go
version.go
version_test.go

This PR adds support for `STRN_LOGGER_SECRET`. Closes #51 and Closes #43
- When set, requests to `STRN_LOGGER_URL` will be sent with 
```
Authorization: Bearer STRN_LOGGER_SECRET
```
- local development works without it, but warning is logged during startup and error is reported in log
- renamed `withUserAgent` to `customTransport` and cleaned up its usage
Next week:

feat: support STRN_LOGGER_SECRET

---

routing.go

Extracted from #59. Adds more logging information on /api/v0/dht/get failure.

refactor: more informative error on /api/v0/dht/get failure

---

lib/graph_gateway.go

This is a quick follow-up fix for #61.
Seems there is no agreement on supporting more than one byte range. This will only prefetch the first range as CAR, and use block-by-block for remaining ones.
In practice, we don't expect to see more than a single range in the real world, video seeking creates a single one etc.
(Merging so staging is ready and will show improved graphs once the other end deploys it.)

fix: single byte range prefetch

---

docs/environment-variables.md
lib/graph_gateway.go

This PR adds support for `car-scope=block|file|all` URL parameter next to the existing-but-confusing-and-only-partially-implemented  `depth=0|1|all`, and always sends both to make Rhea debugging easier.
This will allow Saturn L1/Lassie to migrate without breaking anything during the transition.
For full context and the transition plan see https://github.com/ipfs/bifrost-gateway/issues/80
cc @aarshkshah1992 @willscott @hannahhoward @aschmahmann  @hacdias  @guanzo  for visibility

feat: car-scope support

---

go.mod
go.sum

Update Caboose to the latest main as it has some changes for better tracing of context cancellation errors during retrievals from Saturn and better latency metrics collection.

chore: update caboose (metrics, tracing)

---

blockstore_caboose.go
blockstore_proxy.go
routing.go

By setting `ForceAttemptHTTP2`

fix: ForceAttemptHTTP2 despite custom TLSClientConfig

---

.github/workflows/docker-image.yml

In actions inputs, we need to be explicit with template expansion (`${{}}`).

fix: docker-image workflow when triggered on release

---

version.json

This release uses the same caboose as 0.0.3, but includes fix from #102  
The intention here is to have something that can have `GRAPH_BACKEND=true` enabled if we want, without risk of issues  from #102

chore: 0.0.4

---

docs/environment-variables.md
lib/graph_gateway.go

Ref. https://github.com/ipfs/specs/pull/402
This PR follows a transition plan from #80  to send all versions until every system (lassie, l1) upgrades.

refactor: use IPIP-402 param names when GRAPH_BACKEND=true

---

handlers.go

this will be filled when set as a label per https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/promhttp#InstrumentHandlerResponseSize

feat(metrics): response_size_bytes per HTTP status code

---

lib/graph_gateway.go

Fixes race condition where:
1. Last block in CAR is assigned to `blk`
https://github.com/ipfs/bifrost-gateway/blob/ad571e67e001c71019448831eac93079431fc50b/lib/graph_gateway.go#L336
2. Next call to `cr.Next()` assigns `EOF` to `err`
https://github.com/ipfs/bifrost-gateway/blob/ad571e67e001c71019448831eac93079431fc50b/lib/graph_gateway.go#L336-L339
3. At this point, both `blk` and `err` have a truthy value. `blk` needs to be put in the block store, but `err` is checked first. So the function returns without putting the last block in.
https://github.com/ipfs/bifrost-gateway/blob/ad571e67e001c71019448831eac93079431fc50b/lib/graph_gateway.go#L362-L376

handle block before checking err

---

lib/graph_gateway.go

I believe this fixes the recent `use of closed network connection` error spike that first appeared a day ago on 2023-05-30 15:00:00 UTC, seen on this dashboard. https://protocollabs.grafana.net/d/mdJkp5YVz/caboose-l1-metrics?orgId=1&from=now-2d&to=now&var-interval=5m&var-Environment=production&var-node_id=All&viewPanel=52
The error timing correlates with this deploy https://github.com/protocol/bifrost-infra/pull/2570, which was the first deploy of this commit https://github.com/ipfs/bifrost-gateway/commit/c952ddbd71b69fd535702469fff4bb0764cb0fcb
It's hard to reproduce consistently but once you send enough requests it manifests. Here's some ugly logs
```
---car.NewCarReader rdErr------- context canceled <nil>
--Send block to blkCh-- <nil>
---car.NewCarReader rdErr------- read tcp …
```

return once car reader errors

---

lib/graph_gateway.go

There are various race conditions with pubsub that prevent blocks from being propagated to subscribers.
1. The CAR read finishes and publishes the last few blocks. At the same time, the pubsub instance shuts down because the CAR fetch is done. 
Because `select` chooses a random `case` if multiple are ready, it's possible to choose the `<-ps.closed` case and return, even if `valuesCh` has pending values. We could ensure that the `valuesCh` channel is drained before returning, but let's examine more race conditions.
https://github.com/ipfs/bifrost-gateway/blob/83f1b6f3ddd3e6f24120dc2015c5d1559f4cbb05/lib/pubsub.go#L112-L133
2. It's rare, but the finalizer will delete the notifier before the CAR read is done, which prevents block publishes …

handoffExchange checks shared blockstore right before falling back to block requests

---

go.mod
handlers.go
lib/blockstore_cache.go
lib/graph_gateway.go

This removes the complexity of notifier / shared context between different fetches.
If blocks from a car are not in the order they are requested from the gateway, blocks will be immediately queried to fill any missing gaps.
* I expect this will lead to a significantly higher number of block fetches. i don't know exactly how many.
* I'm interested to see if this changes our observed response sizes

Unshared blockstore

---

Dockerfile

`busybox:1-glibc` got updated yesterday and now `su-exec` used in `entrypoint.sh` segfaults. 
This PR is pinning busybox to older, working version – a quick fix to make sure Docker images are usable.
Staging is  in a reboot loop:
```console
$ docker logs -f bifrost-gw
Changing user to ipfs
Changing user to ipfs
Changing user to ipfs
Changing user to ipfs
Changing user to ipfs
Changing user to ipfs
Changing user to ipfs
Changing user to ipfs
```
I get the same error with ipfs/bifrost-gateway:staging-latest image:
```console
$ docker pull ipfs/bifrost-gateway:staging-latest
[..]
Digest: sha256:889567909465aa8abc55ed5f3ad7285b945c0b2efbbc432dacf758a03e2c6807 
$ docker run --rm -it --net=host -e STRN_ORCHESTRATOR_URL="https://orchestrator.strn.pl/nodes/nearby?count=1000" -e GRAPH_BACKEND=true …
```

fix(docker): segfault in su-exec, pin busybox image

---

Dockerfile

This PR aims to remove  some overengineering around `tini`  and `su-exec` (most likely copied form ipfs-cluster/kubo) 
and use arch-specific prebuilt binaries from alpine + have static binary that is less prone to errors due to annual glibc breakfest.
I've tested this commit in `staging` and produced  `ipfs/bifrost-gateway:staging-2023-06-29-34a5f70`  runs fine on my Rpi4 (ARM64).
The size does not differ much, imo independence of glibc and ARM64 fix are worth it.
```
ipfs/bifrost-gateway:staging-latest	44.8MB (this PR)
ipfs/bifrost-gateway:main-latest	44.1MB (old setup)
```

refactor(docker): simplify Dockerfile, fix arm64

---

blockstore_caboose.go
go.mod
go.sum

- Inject the JWT token used for logging in the orchestrator client to be used for fetching compliance cids from Saturn. 
- Update caboose to version 0.0.3
- Add a config variable to caboose that controls the compliance cid avg request frequency

feat: add auth to saturn orch client

---

go.mod
go.sum
lib/gateway_traversal.go

fix: allow reads with empty car roots

---

.github/workflows/gateway-conformance.yml

Same as https://github.com/ipfs/bifrost-gateway/pull/189 but tests main without https://github.com/ipfs/bifrost-gateway/pull/160

test(main): gateway-conformance with GRAPH_BACKEND=true|false

---

.github/workflows/gateway-conformance.yml

Upload the JSON logs as an artifact that the dashboard generation scripts can retrieve and process.
Support for https://github.com/ipfs/gateway-conformance/pull/146

ci: upload conformance logs

---

blockstore_proxy.go
docs/environment-variables.md
handlers.go
main.go
routing.go

Towards  #151, allows resolving IPNS without `KUBO_RPC_URL` being set
-  adds `IPNS_RECORD_GATEWAY_URL`
- uses either legacy  `KUBO_RPC_URL` or modern `IPNS_RECORD_GATEWAY_URL` or `PROXY_GATEWAY_URL` with support for `application/vnd.ipfs.ipns-record`  responses
Not sure what to do regarding testing here. We haven't had testing before and it seems a bit complicated to automate. I tried locally with both Kubo gateway and Routing V1 and it worked 🥳

feat!: IPNS routing based on IPIP-351 or IPIP-379
